feature(service): Add Whimsical and Figma services
editor-js/embed pull request #123
Opened 2024-03-26 15:30 UTC by thooams

2024-04-03 08:07 UTC, neSpecc commented
@thooams hey. Are you going to update the PR?

2024-04-03 20:29 UTC, thooams commented
Yes. I have to find the time to do it

2024-04-23 09:54 UTC, thooams commented
Tests are written.

2024-07-01 16:27 UTC, neSpecc approved these changes
increment a patch version, please

2024-07-01 16:27 UTC, neSpecc reviewed
Update a list in Readme, please

2024-10-12 13:58 UTC, neSpecc commented
Please, update the branch

2024-10-12 14:00 UTC, neSpecc commented on package.json
> +  "version": "2.8.0",
patch version would be enough

2024-10-12 15:45 UTC, thooams commented on package.json
> +  "version": "2.8.0",
Done

2024-10-12 15:46 UTC, neSpecc commented on package.json
> +  "version": "2.8.0",
use 2.7.7

2024-10-17 14:47 UTC, neSpecc requested changes
please, remove all changes unrelated to new services

2024-10-17 14:47 UTC, neSpecc commented on package.json
> -    "vite-plugin-dts": "^3.9.1"
unexpected change

2024-10-17 14:47 UTC, neSpecc commented on package.json
> -    "@editorjs/editorjs": "^2.29.1"
unexpected change

2024-10-17 14:47 UTC, neSpecc commented on src/services.ts
> -const SERVICES: ServicesConfigType = {
unexpected change

2024-10-17 14:47 UTC, neSpecc commented on src/services.ts
>              return null;
unexpected changes

2024-10-18 08:09 UTC, thooams commented
Unexpected changes were removed

2025-11-21 17:12 UTC, neSpecc approved these changes

2025-11-21 17:13 UTC, merged

2025-11-21 17:14 UTC, neSpecc commented
Thanks @thooams