Pinterest Support
editor-js/embed pull request #40
Opened 2020-09-24 22:11 UTC by Smokietr

2020-10-19 18:58 UTC, yosefanajjar approved these changes

2020-10-19 19:03 UTC, yosefanajjar reviewed
This only handles facebook posts though, what about videos and comments?

2020-10-19 19:23 UTC, yosefanajjar commented
Okay after testing this it works with videos and comments too, really impressed with your work! 👍 
![image](https://user-images.githubusercontent.com/44949822/96501800-94a28400-1259-11eb-9452-a7345497b1c5.png)

The only catch as shown in the image is the spacing between the caption and the actual embedded content which should be a quick styles fix

2020-10-19 19:30 UTC, yosefanajjar commented on src/services.js
> +  },
```suggestion
    id: (e) => {
        return e[1];
    }
  },
```

2020-10-19 19:30 UTC, yosefanajjar commented on src/services.js
> +     }
```suggestion
     id: (e) => {
         return e.join('/');
     }
```

2020-10-20 03:31 UTC, Smokietr commented
Sorry. I have yet to find an answer to this question.

2020-10-20 07:21 UTC, yosefanajjar commented on src/services.js
> +  },
To be more consestant :)
```suggestion
    id: (ids) => {
        return ids[1];
    }
  },
```

2020-10-20 07:21 UTC, yosefanajjar commented on src/services.js
> +     }
```suggestion
     id: (ids) => {
         return ids.join('/');
     }
```

2020-10-20 07:25 UTC, yosefanajjar commented
The space issues seem to be common take a look at this #37

2021-04-02 18:30 UTC, robonetphy commented
Hi @Smokietr, Can you please add the corresponding test case inside [service.js](https://github.com/editor-js/embed/blob/master/test/services.js)

2021-04-21 23:11 UTC, Smokietr commented
Hi @robonetphy Sorry for being late. I work intensely.

2021-04-22 17:34 UTC, robonetphy approved these changes
@Smokietr can you please update the version in the package.json from `2.3.1` -> `2.3.2`.
So we can merge the PR

2021-04-23 17:54 UTC, robonetphy requested changes

2021-04-23 17:54 UTC, robonetphy commented on package.json
>    "keywords": [
@Smokietr Please Change Accordingly.
Sorry for Earlier Typo which is `2.4.2`

2021-04-23 18:06 UTC, robonetphy commented on package.json
>    "keywords": [
And Also Please update [service.md](https://github.com/editor-js/embed/blob/master/docs/services.md)

2021-04-23 18:25 UTC, robonetphy commented
@Smokietr, Also Please Resolve the conflicts and update to the next version accordingly and we ready to merge.

2021-04-24 13:18 UTC, robonetphy commented
@Smokietr please give me access to your repo if you don't have time.Thank you

2021-04-25 17:25 UTC, robonetphy approved these changes

2021-04-25 17:32 UTC, robonetphy approved these changes

2021-04-25 17:35 UTC, robonetphy commented
@Smokietr Thanks for your contribution.

2021-04-25 17:35 UTC, merged