Embed Vimeo if passed an embed URL
editor-js/embed pull request #56
Opened 2021-02-18 15:49 UTC by parterburn

Private Vimeo videos can still be embedded with proper settings, but the REGEX doesn't catch these URL's that look like [`https://player.vimeo.com/video/504749530`.](https://player.vimeo.com/video/504749530.) This PR will catch those and turn them into embeds on EditorJS, as expected.

2021-02-18 15:50 UTC, neSpecc approved these changes

2021-02-18 15:51 UTC, neSpecc requested changes

2021-02-18 15:51 UTC, neSpecc commented on test/services.js
> +      {source: 'https://www.vimeo.com/280712228', embed: 'https://player.vimeo.com/video/280712228?title=0&byline=0'}
```suggestion
      {source: 'https://www.vimeo.com/280712228', embed: 'https://player.vimeo.com/video/280712228?title=0&byline=0'},
```

2021-02-19 04:21 UTC, parterburn commented on src/services.js
> +    regex: /(?:http[s]?:\/\/)?(?:(www|player).)?vimeo\.co(?:.+\/([^\/]\d+)(?:#t=[\d]+)?s?$)/,
```suggestion
    regex: /(?:http[s]?:\/\/)?(?:www.)?(?:player.)?vimeo\.co(?:.+\/([^\/]\d+)(?:#t=[\d]+)?s?$)/,
```

2021-02-19 07:03 UTC, neSpecc approved these changes

2021-03-12 13:40 UTC, neSpecc commented
Increment the patch version, please

2021-04-02 18:31 UTC, robonetphy approved these changes

2021-04-02 18:32 UTC, robonetphy commented
@parterburn you can merge the PR.

2021-04-06 21:06 UTC, parterburn commented
@robonetphy I can't: Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

2021-04-08 16:53 UTC, merged